### ISSUE TITLE
About 'crop_and_center_pcd' in test

### ISSUE THREAD

**Issue by hushbuddy** [liujia99/M3SOT#3]
Hi, I have the same question as @sanfutian https://github.com/liujia99/M3SOT/issues/1#issue-2051778776

It is absolutely wrong to use GT bboxes during testing. I have replaced `tracklet[pre_frame_id]['bbox']` with `pred_bboxes[pre_frame_id]`, resulting in a significant decline in performance compared with the reported results for the KITTI Car dataset in your paper (68.4/79.9 vs 75.9/87.4), by using your provided pretrained weights.

Could you address this issue promptly? It is crucial for maintaining the accuracy of your paper.

**Comment by liujia99** [comment]
Thank you for your attention to our work and your corrections.

As analyzed by you and user @sanfutian, M3SOT is not advisable to use the `tracklet[pre_frame_id]['bbox']` setting during testing. However, since the SOT task aims to explore the bounding boxes in the search area frame, the bounding boxes in the template frame will also be enhanced. Since the prediction result during training is close to the GT bounding box, this has a similar effect to the `pred_bboxes[pre_frame_id]` setting during training.

As for the difference in results you pointed out, this is naturally due to the fact that we are using a multi-template frame strategy. The cumulative deviation of the bounding box gradually becomes larger, resulting in differences in results. The solution is clear and it is recommended that you retrain and test the results.

Additionally, our improvement work on M3SOT is in progress, using the Siamese tracking paradigm, which will explain this phenomenon more powerfully.

Thanks again for your attention and correction. We will revise the relevant content and continue to research this issue.

**Comment by hushbuddy** [comment]
Thanks for your quick reply.

Regardless of the training approach, using GTs during testing is weird and unfair when compared to other methods. I suggest offering a more convincing explanation in the 'Multi-frame SOT' subsection and ensuring a fairer comparison. Thanks.
